[package]
name = "racing_game"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = { version = "0.13", features = ["vulkan"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.7.2"
